/*
  Bible verse repository placeholder.
  Replace this array with your own verse dataset.
  Expected shape:
    { text: "Verse text...", source: "Book Chapter:Verse" }
*/
window.BIBLE_VERSES = [
  { text: "The Lord bless you and keep you; the Lord make his face to shine upon you, and be gracious to you; the Lord lift up his countenance upon you, and give you peace.", source: "Numbers 6:24-26" },
  { text: "Hear, O Israel: The Lord is our God, the Lord alone. You shall love the Lord your God with all your heart, and with all your soul, and with all your might.", source: "Deuteronomy 6:4-5" },
  { text: "Be strong and courageous; do not be frightened or dismayed, for the Lord your God is with you wherever you go.", source: "Joshua 1:9" },
  { text: "The joy of the Lord is your strength.", source: "Nehemiah 8:10" },
  { text: "The Lord is my shepherd, I shall not want. He makes me lie down in green pastures; he leads me beside still waters; he restores my soul.", source: "Psalm 23:1-3" },
  { text: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", source: "Psalm 27:1" },
  { text: "God is our refuge and strength, a very present help in trouble.", source: "Psalm 46:1" },
  { text: "Be still, and know that I am God!", source: "Psalm 46:10" },
  { text: "Your word is a lamp to my feet and a light to my path.", source: "Psalm 119:105" },
  { text: "I lift up my eyes to the hills— from where will my help come? My help comes from the Lord, who made heaven and earth.", source: "Psalm 121:1-2" },
  { text: "The fear of the Lord is the beginning of knowledge; fools despise wisdom and instruction.", source: "Proverbs 1:7" },
  { text: "Trust in the Lord with all your heart, and do not rely on your own insight. In all your ways acknowledge him, and he will make straight your paths.", source: "Proverbs 3:5-6" },
  { text: "Those who wait for the Lord shall renew their strength, they shall mount up with wings like eagles, they shall run and not be weary, they shall walk and not faint.", source: "Isaiah 40:31" },
  { text: "But now thus says the Lord, he who created you, O Jacob, he who formed you, O Israel: Do not fear, for I have redeemed you; I have called you by name, you are mine.", source: "Isaiah 43:1" },
  { text: "For surely I know the plans I have for you, says the Lord, plans for your welfare and not for harm, to give you a future with hope.", source: "Jeremiah 29:11" },
  { text: "The steadfast love of the Lord never ceases, his mercies never come to an end; they are new every morning; great is your faithfulness.", source: "Lamentations 3:22-23" },
  { text: "Return to the Lord, your God, for he is gracious and merciful, slow to anger, and abounding in steadfast love.", source: "Joel 2:13" },
  { text: "He has told you, O mortal, what is good; and what does the Lord require of you but to do justice, and to love kindness, and to walk humbly with your God?", source: "Micah 6:8" },
  { text: "Let your light shine before others, so that they may see your good works and give glory to your Father in heaven.", source: "Matthew 5:16" },
  { text: "But strive first for the kingdom of God and his righteousness, and all these things will be given to you as well.", source: "Matthew 6:33" },
  { text: "Come to me, all you that are weary and are carrying heavy burdens, and I will give you rest. Take my yoke upon you, and learn from me; for I am gentle and humble in heart, and you will find rest for your souls. For my yoke is easy, and my burden is light.", source: "Matthew 11:28-30" },
  { text: "'You shall love the Lord your God with all your heart, and with all your soul, and with all your mind.' This is the greatest and first commandment. And a second is like it: 'You shall love your neighbor as yourself.'", source: "Matthew 22:37-39" },
  { text: "Jesus came and said to them, \"All authority in heaven and on earth has been given to me. Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, and teaching them to obey everything that I have commanded you. And remember, I am with you always, to the end of the age.\"", source: "Matthew 28:18-20" },
  { text: "The time is fulfilled, and the kingdom of God has come near; repent, and believe in the good news.", source: "Mark 1:15" },
  { text: "But the angel said to them, \"Do not be afraid; for see—I am bringing you good news of great joy for all the people: to you is born this day in the city of David a Savior, who is the Messiah, the Lord. This will be a sign for you: you will find a child wrapped in bands of cloth and lying in a manger.\"", source: "Luke 2:10-12" },
  { text: "And the Word became flesh and lived among us, and we have seen his glory, the glory as of a father's only son, full of grace and truth.", source: "John 1:14" },
  { text: "For God so loved the world that he gave his only Son, so that everyone who believes in him may not perish but may have eternal life. Indeed, God did not send the Son into the world to condemn the world, but in order that the world might be saved through him.", source: "John 3:16-17" },
  { text: "Jesus said to them, \"I am the bread of life. Whoever comes to me will never be hungry, and whoever believes in me will never be thirsty.\"", source: "John 6:35" },
  { text: "Jesus spoke to them, saying, \"I am the light of the world. Whoever follows me will never walk in darkness but will have the light of life.\"", source: "John 8:12" },
  { text: "Do not let your hearts be troubled. Believe in God, believe also in me. In my Father's house there are many dwelling places. If it were not so, would I have told you that I go to prepare a place for you? And if I go and prepare a place for you, I will come again and will take you to myself, so that where I am, there you may be also.", source: "John 14:1-3" },
  { text: "Peace I leave with you; my peace I give to you. I do not give to you as the world gives. Do not let your hearts be troubled, and do not let them be afraid.", source: "John 14:27" },
  { text: "I am the true vine, and my Father is the vinegrower. He removes every branch in me that bears no fruit. Every branch that bears fruit he prunes to make it bear more fruit.", source: "John 15:1-2" },
  { text: "The Spirit helps us in our weakness; for we do not know how to pray as we ought, but that very Spirit intercedes with sighs too deep for words. And God, who searches the heart, knows what is the mind of the Spirit, because the Spirit intercedes for the saints according to the will of God.", source: "Romans 8:26-27" },
  { text: "We know that all things work together for good for those who love God, who are called according to his purpose.", source: "Romans 8:28" },
  { text: "Do not be conformed to this world, but be transformed by the renewing of your minds, so that you may discern what is the will of God—what is good and acceptable and perfect.", source: "Romans 12:2" },
  { text: "So, whether you eat or drink, or whatever you do, do everything for the glory of God.", source: "1 Corinthians 10:31" },
  { text: "Love is patient; love is kind; love is not envious or boastful or arrogant or rude. It does not insist on its own way; it is not irritable or resentful; it does not rejoice in wrongdoing, but rejoices in the truth. It bears all things, believes all things, hopes all things, endures all things. Love never ends.", source: "1 Corinthians 13:4-8" },
  { text: "The grace of the Lord Jesus Christ, the love of God, and the communion of the Holy Spirit be with all of you.", source: "2 Corinthians 13:13" },
  { text: "So if anyone is in Christ, there is a new creation: everything old has passed away; see, everything has become new!", source: "2 Corinthians 5:17" },
  { text: "It is no longer I who live, but it is Christ who lives in me. And the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me.", source: "Galatians 2:20" },
  { text: "The fruit of the Spirit is love, joy, peace, patience, kindness, generosity, faithfulness, gentleness, and self-control.", source: "Galatians 5:22-23" },
  { text: "For by grace you have been saved through faith, and this is not your own doing; it is the gift of God— not the result of works, so that no one may boast.", source: "Ephesians 2:8-9" },
  { text: "I can do all things through him who strengthens me.", source: "Philippians 4:13" },
  { text: "Rejoice in the Lord always; again I will say, Rejoice. Let your gentleness be known to everyone. The Lord is near. Do not worry about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.", source: "Philippians 4:4-7" },
  { text: "So if you have been raised with Christ, seek the things that are above, where Christ is, seated at the right hand of God. Set your minds on things that are above, not on things that are on earth, for you have died, and your life is hidden with Christ in God.", source: "Colossians 3:1-3" },
  { text: "Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you.", source: "1 Thessalonians 5:16-18" },
  { text: "All scripture is inspired by God and is useful for teaching, for reproof, for correction, and for training in righteousness.", source: "2 Timothy 3:16" },
  { text: "I have fought the good fight, I have finished the race, I have kept the faith.", source: "2 Timothy 4:7" },
  { text: "Now faith is the assurance of things hoped for, the conviction of things not seen.", source: "Hebrews 11:1" },
  { text: "Therefore, since we are surrounded by so great a cloud of witnesses, let us also lay aside every weight and the sin that clings so closely, and let us run with perseverance the race that is set before us.", source: "Hebrews 12:1" },
  { text: "Cast all your anxiety on him, because he cares for you.", source: "1 Peter 5:7" },
  { text: "Listen! I am standing at the door, knocking; if you hear my voice and open the door, I will come in to you and eat with you, and you with me.", source: "Revelation 3:20" },
];
