name = "sampires-glorious-typing-test"
main = "worker.js"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."

[[routes]]
pattern = "type.sherathia.com"
zone_name = "sherathia.com"
custom_domain = true

[[kv_namespaces]]
binding = "TYPING_APP"
id = "a1574fd2943b4f0c8748849a98cad7fd"
